
name: upload_to_gcs
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup - gcloud / gsutil
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT }}
        export_default_credentials: true

    - name: Upload
      run: |-
        gsutil -m rsync -R ./epidemic/*.csv gs://${{ secrets.GCS_BUCKET }}/epidemic/
        gsutil -m rsync -R ./mysejahtera/*.csv gs://${{ secrets.GCS_BUCKET }}/mysejahtera/
        gsutil -m rsync -R ./static/*.csv gs://${{ secrets.GCS_BUCKET }}/static/
          
