
name: upload_to_gcs
env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup - gcloud / gsutil
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT }}
        export_default_credentials: true

    - name: Upload
      run: |-
        gsutil -m rsync -R output gs://$GCS_BUCKET
          
